[General]
BrowserApplication=firefox.desktop
TerminalApplication=konsole
TerminalService=org.kde.konsole.desktop

[Wallpapers]
usersWallpapers=/usr/share/wallpapers/CentrexOS/

[Compositing]
AnimationSpeed=3
Backend=OpenGL
Enabled=true
GLColorCorrection=false
GLPreferBufferSwap=a
GLTextureFilter=2
HiddenPreviews=5
OpenGLIsUnsafe=false
WindowsBlockCompositing=true
XRenderSmoothScale=false

[ScreenEdges]
Bottom=0
BottomLeft=0
BottomRight=0
Left=0
Right=0
Top=0
TopLeft=0
TopRight=0

[Multihead]
MaximizeOnlyOnCurrentScreen=false

[Theme]
name=CentrexDark
